# Generated by Django 5.1.4 on 2025-03-18 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default project', max_length=128, verbose_name='Название')),
                ('url_repo', models.URLField(blank=True, verbose_name='Репозиторий с проектом')),
            ],
        ),
        migrations.CreateModel(
            name='TODOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст заметки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created todo')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated todo')),
                ('deleted', models.BooleanField(default=False, verbose_name='Deleted todo')),
                ('active', models.BooleanField(default=False, verbose_name='Активность заметки')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
