# Generated by Django 5.1.4 on 2025-02-07 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_projectmodel_users_alter_todomodel_deleted'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectmodel',
            name='name',
            field=models.CharField(default='Default project', max_length=128, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активность заметки'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.projectmodel', verbose_name='Проект'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='text',
            field=models.TextField(verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='todomodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кто пишет заметку'),
        ),
    ]
