# Generated by Django 5.1.4 on 2025-01-04 22:23

from django.db import migrations

def forward_func(apps, schema_editor):
    user_model = apps.get_model('usersapp', 'CustomUser')
    first_names = ['John', 'Bob', 'Kate']
    last_names = ['Smith', 'Miller', 'Rihter']
    emails = ['smith@mail.ru', 'miller@mail.ru', 'rihter@inbox.ru']
    usernames = ['jo', 'bo', 'ka']
    for data in range(3):
        user_model.objects.create(
            first_name = first_names[data],
            last_name = last_names[data],
            email = emails[data],
            username = usernames[data]
        )

def reverse_func(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
