# Generated by Django 5.1.4 on 2025-03-19 20:35

from django.db import migrations

def forward_func(apps, schema_editor):
    user_model = apps.get_model('usersapp', 'CustomUser')

    user_model.objects.create(
        first_name = 'Ivan',
        last_name = 'Petrov',
        email = 'vanya@mail.ru'
    )

def reverse_func(apps, schema_editor):
    ...

class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
