# Generated by Django 5.1.4 on 2025-03-19 20:39

from django.db import migrations

def forward_func(apps, schema_editor):
    user_model = apps.get_model('usersapp', 'CustomUser')

    user_model.objects.create(
        first_name = 'Dima',
        last_name = 'Vaskov',
        email = 'dima@mail.ru'
    )

def reverse_func(apps, schema_editor):
    ...



class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0003_auto_20250319_2335'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
