# Generated by Django 5.1.4 on 2025-03-23 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0004_auto_20250319_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(blank=True, default='not username, email: <django.db.models.fields.CharField>', max_length=32, unique=True),
        ),
    ]
