# Generated by Django 5.1.4 on 2025-03-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0005_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='NOT username, email: <django.db.models.fields.CharField>', max_length=32, unique=True),
        ),
    ]
