# Generated by Django 5.1.4 on 2025-04-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0007_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='test_date',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
