# Generated by Django 5.1.4 on 2024-12-25 20:17

from django.db import migrations, connection



def forward_func(apps, schema_editor):
    author = apps.get_model('authors_app', 'Author')
    first_names = ['Янис', 'Локи']
    last_names = ['Микульскис', 'Брусникин']
    birthday_year = [1995, 2015]
    usernames = ['hustle37', 'cat']
    id_list = [2,3]
    for i in range(2):
        author.objects.create(
            id = id_list[i],
            first_name = first_names[i],
            last_name = last_names[i],
            birthday = birthday_year[i],
            username = usernames[i],
        )

def reverse_func(apps, schema_editor):
    author = apps.get_model('authors_app', 'Author')
    print(f'fafsafasfas')

    for i in range(4, 7):
        author.objects.get(id=i).delete()

    max_id = author.objects.order_by('-id').first().id if author.objects.exists() else 0
    with connection.cursor() as cursor:
        cursor.execute('UPDATE sqlite_sequence SET seq = :seq WHERE name = :name', {'seq':max_id, 'name':'authors_app_author'})



class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
