# Generated by Django 5.1.4 on 2024-12-26 18:15

from django.db import migrations

def forward_func(apps, schema_editor):
    author = apps.get_model('authors_app', 'Author')
    author.objects.get(id=7).delete()

def reverse_func(apps, schema_editor):
    pass
class Migration(migrations.Migration):

    dependencies = [
        ('authors_app', '0002_data_migrations'),
    ]

    operations = [
        migrations.RunPython(
            forward_func,
            reverse_func
        )
    ]
